name: Main
version: '1.0-SNAPSHOT'
main: com.nik.sample.Main
api-version: '1.21'
commands:
  inv:
    description: Get Inventory of specified player
  hat:
    description: Equip your current item as a hat

  lock:
    description: Lock a chest with a password
  unlock:
    description: Unlock a locked chest with a password
  saveconf:
    description: Save the configuration