name: Update Daily Gif

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  append:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: +1 on the current gif name
        # only run when workflow is started as schedule, to start the workflow once to start the cronjob.
        if: ${{ github.event_name == 'schedule' }}
        run: |
          zahl=$(cat README.md | grep -o -P -m 1 '(?<=Tag_)[1-4]') && zahl=$((zahl + 1)) && sed -i "s/Tag_[1-4]\b/Tag_$zahl/" README.md

      - name: Commit and push changes
        # only run when workflow is started as schedule, to start the workflow once to start the cronjob.
        if: ${{ github.event_name == 'schedule' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Automatisches Update: $(date)" || echo "Nichts zu committen"
          git push
